id = "vantadark-theme"
name = "Vantadark"
version = "2.0.0"
schema_version = 1
description = "Clean surfaces, minimal yet subtle border lines, five syntax colours. Enough to tell your code apart, not enough to distract you from it."
repository = "https://github.com/ams-sth/vantadark"
authors = ["Amsh Shrestha <sthaamsh37@gmail.com>"]
themes = ["themes/vantadark.json"]
