id = "vantadark-theme"
name = "Vantadark"
version = "1.1.5"
schema_version = 1
description = "A minimal dark theme for Zed. Clean surfaces, no borders, five syntax colours. Gets out of the way."
repository = "https://github.com/ams-sth/vantadark"
authors = ["Amsh Shrestha <sthaamsh37@gmail.com>"]
themes = ["themes/vantadark.json"]
